import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          "50": "#FFF4DE",
          "100": "#FED47C",
          "200": "#FFBF39",
          "500": "#F6A600",
          "600": "#B97C00",
          "800": "#7B5300",
          "900": "#3E2A00",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          "50": "#CCE4FD",
          "100": "#9BC9F9",
          "200": "#56A1F7",
          "500": "#3079DB",
          "600": "#015AAA",
          "700": "#18457C",
          "900": "#021C48",
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        shades: {
          "1": "#FFFFFF",
          "100": "#000000",
        },
        neutral: {
          "50": "#F6F5F3",
          "100": "#ECEAE5",
          "200": "#D7D4CB",
          "500": "#AFA795",
          "600": "#585243",
          "800": "#3B362C",
          "900": "#1D1B16",
        },
        icon: {
          "50": "#D9FCD6",
          "100": "#047420",
          "200": "#680305",
          "300": "#F9AEAF",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      spacing: {
        "1": "2px",
        "2": "4px",
        "3": "8px",
        "4": "12px",
        "5": "16px",
        "6": "24px",
        "7": "32px",
        "8": "40px",
        "9": "48px",
        "10": "64px",
        "11": "80px",
        "12": "96px",
        "13": "160px",
      },
      fontSize: {
        h1: "28px",
        h2: "25px",
        h3: "22px",
        sub: "18px",
        base: "16px",
        sm: "14px",
        cap: "12px",
      },
      lineHeight: {
        sm: "21px",
        cap: "29.2px",
        base: "22.4px",
        sub: "17.6px",
        h3: "19.8px",
        h2: "27.5",
        h1: "30.8px",
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        bold: "700",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
