import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        yellow: {
          "50": "#FFF4DE",
          "100": "#FED47C",
          "200": "#FFBF39",
          "500": "#F6A600",
          "600": "#B97C00",
          "800": "#7B5300",
          "900": "#3E2A00",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        blue: {
          "10": "#EBF2FA",
          "50": "#CCE4FD",
          "100": "#9BC9F9",
          "200": "#56A1F7",
          "500": "#3079DB",
          "600": "#015AAA",
          "700": "#18457C",
          "900": "#021C48",
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        green: {
          "500": "#4A806A",
        },
        shades: {
          "1": "#FFFFFF",
          "100": "#000000",
        },
        grey: {
          "0": "#FFFFFF",
          "10": "#F9FAFB",
          "50": "#F3F5F6",
          "100": "#E5E8EC",
          "200": "#CBD1D7",
          "500": "#97A0AA",
          "600": "#434D58",
          "800": "#2C333B",
          "900": "#16191D",
        },
        error: {
          "50": "#931010",
          "30": "#E51F1F",
          "10": "#F1E6E6",
        },
        orange: {
          "50": "#F58600",
          "10": "#FEF3E5",
        },
        success: {
          "70": "#055418",
          "50": "#047420",
          "20": "#E6F1E9",
        },

        icon: {
          "50": "#E1F8E6",
          "100": "#047420",
          "200": "#680305",
          "300": "#F6E3E3",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      spacing: {
        "1": "2px",
        "2": "4px",
        "3": "8px",
        "4": "12px",
        "5": "16px",
        "6": "24px",
        "7": "32px",
        "8": "40px",
        "9": "48px",
        "10": "64px",
        "11": "80px",
        "12": "96px",
        "13": "160px",
      },
      fontSize: {
        h1: "28px",
        h2: "25px",
        h3: "22px",
        sub: "18px",
        base: "16px",
        sm: "14px",
        cap: "12px",
      },
      lineHeight: {
        sm: "21px",
        cap: "29.2px",
        base: "22.4px",
        sub: "17.6px",
        h3: "19.8px",
        h2: "27.5",
        h1: "30.8px",
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        bold: "700",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
